name: 'DevOps Common Lib'
description: 'Build tools and run commands inside CI container'
inputs:
  image_name:
    description: 'Nombre de la imagen de herramientas CI'
    required: true
  run_command:
    description: 'Comando a ejecutar dentro del contenedor'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build CI tools image
      shell: bash
      run: |
        docker build -t ${{ inputs.image_name }} -f devops/ci.Dockerfile .

    - name: Execute command in CI container
      shell: bash
      run: |
        echo "Esquivando el problema de volúmenes DinD con copia directa..."
        CID=$(docker create -w /app ${{ inputs.image_name }} ${{ inputs.run_command }})
        docker cp . $CID:/app/
        docker start -a $CID
        EXIT_CODE=$(docker inspect $CID --format='{{.State.ExitCode}}')
        docker rm $CID
        exit $EXIT_CODE
